### ISSUE TITLE
Not a single cam loads (they are not even listed)

### ISSUE THREAD

**Issue by cffm** [idleloop-github/xbmc-earthcam#1]
Using this on the latest Kodi and I see USA, Worldwide and all that. But each folder is empty.

Is this just me? Also, had to clean install Kodi and same issue...

**Comment by swimminsparrow** [comment]
Same problem. I thought it was an incompatibility issue with Kodi 17 but after i downgraded to kodi 16 the same problem. I think it could be related to new https protocol of earthcam website

**Comment by idleloop-github** [comment]
The problem is that the html code at the web site has changed, so the addon must be updated.
It'll take some work...

PS: it is not an https web issue: that was patched on the last version.

**Comment by idleloop-github** [comment]
Still working on a new version.

Additionally, the addon "**inputstream.rtmp**" seems less functional now: on some platforms (Windows) earthcam cams don't connect when they previously did, and in some other platforms (arm) libressl libraries must be correctly linked. 
**This can be checked simply using your "favorites" links** if you had any. These links are still functional, so if you can't connect then there's a problem with "inputstream.rtmp" that didn't exist before.

Maybe another version update of "inputstream.rtmp" is needed, but I'm not sure (and I do not control that), so maybe some platforms won't have a functional earthcam addon even after the new version. Still checking.

**Comment by idleloop-github** [comment]
I've released a quick patch named [v 1.1.0](https://github.com/idleloop-github/xbmc-earthcam/releases/download/v1.1.0/plugin.video.earthcam-1.1.0.zip).

The README contains instructions for RTMP activation and patch intent in case no cam functions... Anyway, any RTMP issues cannot be patched by code here.

**Comment by cffm** [comment]
Thanks for the update. It does not work for me though. I am running it on PI3. RTMP is enabled. I tried to update it (as suggested in the readme) but it is not in the kodinerds repo.

Not working on RPI then?

**Comment by idleloop-github** [comment]
@cffm : Raspberry Pi 3 is compatible with RPi 2 rtmp at kodinerds: [try it](https://github.com/kodinerds/binary-repo/raw/master/offline/RPi2/inputstream.rtmp/inputstream.rtmp-1.0.4.zip). This should run for RPis!

For other platforms in problems with rtmp (Windows, for example), I've released [v1.2.0](https://github.com/idleloop-github/xbmc-earthcam/releases/download/v1.1.0/plugin.video.earthcam-1.2.0.zip) - with it, **[HLS protocol](https://en.wikipedia.org/wiki/HTTP_Live_Streaming)** can be activated in the add-on's configuration: this can (hopefully) patch the cams for those platforms.

I'm not sure if HLS runs with RPi2 & RPi3. Try it and tell us!

**Comment by idleloop-github** [comment]
Seems patched for now.
Thanks to all of you for your comments.
