### ISSUE TITLE
User interface locks when stream is not served

### ISSUE THREAD

**Issue by kekukui** [idleloop-github/xbmc-earthcam#3]
If the stream server does not respond, Estuary's "busy" indicator remains on screen forever -- it is not possible to regain control of Kodi.  Home & Back buttons do not work.  (This is not just a bug in the app, its also a design flaw in Kodi.)
____________

Currently not working streams, to reproduce this bug:

- Elvis wedding chapel
- Bellagio conservatory

```
9:04:33.708 NOTICE: VideoPlayer: Opening: rtmp://videos3.earthcam.com/ app=fecnetwork swfUrl=http://www.earthcam.com/swf/cam_player_v2/ecnPlayer.swf playpath=5359.flv live=true timeout=180
9:04:33.708 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
9:04:33.709 NOTICE: Creating InputStream
9:04:38.007 NOTICE: Creating Demuxer
9:08:34.744 ERROR: ADDON: extension '' is not currently supported for service addon

```
[No more messages appear in log after waiting a long time]

**Comment by idleloop-github** [comment]
Hi @h3298 ,
Thanks for the report: Yeah, I know that annoying one... and I haven't deal with it yet... Any hint or pull request will be considered!

**Comment by idleloop-github** [comment]
Hi @h3298 ,
Thanks for the report: Yeah, I know that annoying one... and I haven't dealt with it yet... due to lack of time! Any hint or pull request will be considered!

**Comment by kekukui** [comment]
I understand.  Working on audio streaming / Leia compatibility issues at the moment but did want to document this issue because I would forget about it  ;-)

**Comment by idleloop-github** [comment]
I think I've [patched this bug](https://github.com/idleloop-github/xbmc-earthcam/commit/d76457b80c5924dd7d281590da13e888a9a6bceb) in [v1.3.0](https://github.com/idleloop-github/xbmc-earthcam/releases/tag/v1.3.0):
It was as easy as to reduce the passed timeout parameter in the rtmp connection string :_(
I've reduced it from 180s to 10s. This makes the GUI more fluid.
